const express = require("express")

const userRoutes = require("./user_routes")
const aRoutes = require("./a_routes")
const bRoutes = require("./b_routes")
const cRoutes = require("./c_routes")
const dRoutes = require("./d_routes")
const eRoutes = require("./e_routes")
const fRoutes = require("./f_routes")
const gRoutes = require("./g_routes")
const hRoutes = require("./h_routes")
const iRoutes = require("./i_routes")
const jRoutes = require("./j_routes")
const kRoutes = require("./k_routes")
const lRoutes = require("./l_routes")
const mRoutes = require("./m_routes")
const nRoutes = require("./n_routes")
const oRoutes = require("./o_routes")
const pRoutes = require("./p_routes")
const qRoutes = require("./q_routes")
const rRoutes = require("./r_routes")
const sRoutes = require("./s_routes")
const tRoutes = require("./t_routes")
const uRoutes = require("./u_routes")
const vRoutes = require("./v_routes")
const wRoutes = require("./w_routes")
const foodRoutes = require("./food_routes")

const router = express()

router.use("/user",userRoutes)
router.use("/a",aRoutes)
router.use("/b",bRoutes)
router.use("/c",cRoutes)
router.use("/d",dRoutes)
router.use("/e",eRoutes)
router.use("/f",fRoutes)
router.use("/g",gRoutes)
router.use("/h",hRoutes)
router.use("/i",iRoutes)
router.use("/j",jRoutes)
router.use("/k",kRoutes)
router.use("/l",lRoutes)
router.use("/m",mRoutes)
router.use("/n",nRoutes)
router.use("/o",oRoutes)
router.use("/p",pRoutes)
router.use("/q",qRoutes)
router.use("/r",rRoutes)
router.use("/s",sRoutes)
router.use("/t",tRoutes)
router.use("/u",uRoutes)
router.use("/v",vRoutes)
router.use("/w",wRoutes)
router.use("/food",foodRoutes)

module.exports = router